Module8 task1
htmlacademy-javascript/1036301-keksobooking-22 pull request #10
Opened 2021-03-02 04:56 UTC by sakralbar0192

2021-03-02 05:20 UTC, phwb requested changes
почему в квартире минимальная цена 5000? должно быть 1000
![image](https://user-images.githubusercontent.com/4672733/109601440-b59caf00-7b40-11eb-955d-2d4c42c87815.png)

2021-03-02 05:20 UTC, phwb commented on js/api.js
> +      onError(MESSAGE_DISPLAY_TIME);
сразу скажу что это не самы лучший метод детектить ошибку. catch возвращает описание ошибки, лучше пользоваться им. мне оно не принципиально, главное чтобы ошибка отлавливалась, но проверяющий может докопаться

2021-03-02 05:20 UTC, phwb commented on js/form.js
> +      if (allowedValues.some((value) => {
вынеси в переменную выполнение some, читаться будет лучше

2021-03-02 05:20 UTC, phwb commented on js/form.js
> +synchronizeField(addFormTimeIn, addFormTimeOut);
опять таки, логика должна быть сосредоточена в main

2021-03-02 05:20 UTC, phwb commented on js/form.js
> +export {resetForm, addressField, addForm};
лучше не экспортировать дом элементы, экспортируй функции для работы с ними. с точки зрения архитектуры так правильнее

2021-03-02 05:20 UTC, phwb commented on js/map-filtering-form.js
> +    filteredData = data.filter((object) => {
на проверке могут докопаться за использование нескольких filter, эту задачу можно решить одним. опять таки мне не принципиально, пока можешь не делать, но имей в виду, что могу попросить переделать

2021-03-02 05:20 UTC, phwb commented on js/map-filtering-form.js
> +  (currentValue != 'any')
упрости выражение
```jsx
const filteredData = currentValue != 'any' ? ... : ...;
```

2021-03-02 05:20 UTC, phwb commented on js/map-filtering-form.js
> +    filteredData = data.filter((object) => {
аналогично про filter

2021-03-02 05:25 UTC, sakralbar0192 commented on js/api.js
> +      onError(MESSAGE_DISPLAY_TIME);
не совсем понял этот момент: лучше пользоваться описанием ошибки, которое возвращает catch, а не функцией внутри нее?

2021-03-03 09:47 UTC, phwb approved these changes

2021-03-03 09:47 UTC, merged